---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: crystal-release
- name: semver

outputs:
- name: version-tag
- name: finalized-release

params:
  BLOBSTORE_ACCESS_KEY_ID: ~
  BLOBSTORE_SECRET_ACCESS_KEY: ~
  GIT_USER_EMAIL: ~
  GIT_USER_NAME: ~

run:
  path: crystal-release/ci/tasks/finalize.sh
