---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: crystal-release
- name: stemcell

run:
  path: crystal-release/ci/tasks/run-tests.sh
